sudo: required
os: linux
dist: trusty
services:
  - docker
env:
  matrix:
    - proxy=default_release build_args="-C Release --skip-unittests --use-zlog"
    - proxy=no_zlog_release build_args="-C Release --skip-unittests"
    - proxy=default_debug build_args="-C Debug --use-zlog"
    - proxy=no_zlog_debug build_args="-C Debug"
language: c
compiler: 
  - gcc
  - clang
install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.4 -y
script: "bash bld/build.sh -c $build_args"
